### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by chirag-jn** [design3602019/design3602019.github.io#6]
https://github.com/design3602019/design3602019.github.io/blob/b3f5671e976183fb5c1f2ae72c0a06f0a9a17a72/index.html#L79

Add a popup for now, saying that registration will open soon. stay tuned.

**Comment by design3602019** [comment]
added a new page

**Comment by chirag-jn** [comment]
Add a popup instead of opening a whole new page. 
https://www.w3schools.com/js/js_popup.asp
